name: bmi_calculator_2
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.1.0
  firebase_core: ^1.21.1
  cloud_firestore: ^3.4.6
  firebase_auth: ^3.3.11
  google_sign_in: ^5.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true
  assets:
    - image/
